swagger: '2.0'
info:
  title: Kujira API
  version: 1.0.0
paths:
  /:
    get:
      description: Returns information about the Kujira API
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              chain:
                type: string
              network:
                type: string
              connector:
                type: string
              connection:
                type: boolean
              timestamp:
                type: integer
  /token:
    get:
      description: Retrieves information about a specific token
      parameters:
        - in: query
          name: tokenAddress
          description: The address of the token
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TokenResponse'
  /tokens:
    get:
      description: Retrieves information about multiple tokens
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TokensResponse'
  /tokens/all:
    get:
      description: Retrieves information about all tokens
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AllTokensResponse'
  /market:
    get:
      description: Retrieves information about a specific market
      parameters:
        - in: query
          name: marketId
          description: The ID of the market
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MarketResponse'
#  /markets:
#    get:
#      description: Retrieves information about multiple markets
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/MarketsResponse'
#  /markets/all:
#    get:
#      description: Retrieves information about all markets
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/AllMarketsResponse'
#  /orderBook:
#    get:
#      description: Retrieves the order book for a specific market
#      parameters:
#        - in: query
#          name: marketId
#          description: The ID of the market
#          required: true
#          type: string
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/OrderBookResponse'
#  /orderBooks:
#    get:
#      description: Retrieves the order books for multiple markets
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/OrderBooksResponse'
#  /orderBooks/all:
#    get:
#      description: Retrieves the order books for all markets
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/AllOrderBooksResponse'
#  /ticker:
#    get:
#      description: Retrieves the ticker for a specific market
#      parameters:
#        - in: query
#          name: marketId
#          description: The ID of the market
#          required: true
#          type: string
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/TickerResponse'
#  /tickers:
#    get:
#      description: Retrieves the tickers for multiple markets
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/TickersResponse'
#  /ticker/all:
#    get:
#      description: Retrieves the tickers for all markets
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/AllTickersResponse'
#  /balance:
#    get:
#      description: Retrieves the balance for a specific token
#      parameters:
#        - in: query
#          name: tokenAddress
#          description: The address of the token
#          required: true
#          type: string
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/BalanceResponse'
#  /balances:
#    get:
#      description: Retrieves the balances for multiple tokens
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/BalancesResponse'
#  /balances/all:
#    get:
#      description: Retrieves the balances for all tokens
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/AllBalancesResponse'
#  /order:
#    get:
#      description: Retrieves information about a specific order
#      parameters:
#        - in: query
#          name: orderId
#          description: The ID of the order
#          required: true
#          type: string
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/OrderResponse'
#    post:
#      description: Places a new order
#      parameters:
#        - in: body
#          name: order
#          description: The order details
#          required: true
#          schema:
#            $ref: '#/definitions/PlaceOrderRequest'
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/PlaceOrderResponse'
#    delete:
#      description: Cancels a specific order
#      parameters:
#        - in: body
#          name: order
#          description: The order details
#          required: true
#          schema:
#            $ref: '#/definitions/CancelOrderRequest'
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/CancelOrderResponse'
#  /orders:
#    get:
#      description: Retrieves information about multiple orders
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/OrdersResponse'
#    post:
#      description: Places multiple orders
#      parameters:
#        - in: body
#          name: orders
#          description: The list of order details
#          required: true
#          schema:
#            $ref: '#/definitions/PlaceOrdersRequest'
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/PlaceOrdersResponse'
#    delete:
#      description: Cancels multiple orders
#      parameters:
#        - in: body
#          name: orders
#          description: The list of order details
#          required: true
#          schema:
#            $ref: '#/definitions/CancelOrdersRequest'
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/CancelOrdersResponse'
#  /orders/all:
#    delete:
#      description: Cancels all orders
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/CancelAllOrdersResponse'
#  /market/withdraw:
#    post:
#      description: Withdraws funds from a specific market
#      parameters:
#        - in: body
#          name: withdraw
#          description: The withdrawal details
#          required: true
#          schema:
#            $ref: '#/definitions/MarketWithdrawRequest'
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/MarketWithdrawResponse'
#  /market/withdraws:
#    post:
#      description: Withdraws funds from multiple markets
#      parameters:
#        - in: body
#          name: withdraws
#          description: The list of withdrawal details
#          required: true
#          schema:
#            $ref: '#/definitions/MarketsWithdrawsRequest'
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/MarketsWithdrawsFundsResponse'
#  /market/withdraws/all:
#    post:
#      description: Withdraws funds from all markets
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/AllMarketsWithdrawsResponse'
#  /transaction:
#    get:
#      description: Retrieves information about a specific transaction
#      parameters:
#        - in: query
#          name: transactionId
#          description: The ID of the transaction
#          required: true
#          type: string
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/TransactionResponse'
#  /transactions:
#    get:
#      description: Retrieves information about multiple transactions
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/TransactionsResponse'
#  /wallet/publicKey:
#    get:
#      description: Retrieves the public key of the wallet
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/WalletPublicKeyResponse'
#  /wallet/publicKeys:
#    get:
#      description: Retrieves the public keys of multiple wallets
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/WalletsPublicKeysResponse'
#  /block/current:
#    get:
#      description: Retrieves information about the current block
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/CurrentBlockResponse'
#  /fees/estimated:
#    get:
#      description: Retrieves information about the estimated fees
#      responses:
#        '200':
#          description: OK
#          schema:
#            $ref: '#/definitions/EstimatedFeesResponse'
definitions:
  TokenResponse:
    $ref: './definitions.yml#/definitions/KujiraTokenResponse_1'

  TokensResponse:
    type: "object"
    properties:
      ukuji:
        $ref: './definitions.yml#/definitions/KujiraTokenResponse_1'
      factory/kujira1r85reqy6h0lu02vyz0hnzhv5whsns55gdt4w0d7ft87utzk7u0wqr4ssll/uusk:
        $ref: './definitions.yml#/definitions/KujiraTokenResponse_2'

  AllTokensResponse:
    type: "object"
    properties:
      ukuji:
        $ref: './definitions.yml#/definitions/KujiraTokenResponse_1'
      "factory/kujira1ltvwg69sw3c5z99c6rr08hal7v0kdzfxz07yj5/demo":
        $ref: './definitions.yml#/definitions/KujiraTokenResponse_2'
      "factory/kujira1r85reqy6h0lu02vyz0hnzhv5whsns55gdt4w0d7ft87utzk7u0wqr4ssll/uusk":
        $ref: './definitions.yml#/definitions/KujiraTokenResponse_3'
      "ibc/F91EA2C0A23697A1048E08C2F787E3A58AC6F706A1CD2257A504925158CFC0F3":
        $ref: './definitions.yml#/definitions/KujiraTokenResponse_4'
  MarketResponse:
    properties:
      id:
        type: string
        example: "kujira1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrsqq4jjh"
      name:
        type: string
        example: "KUJI/DEMO"
      baseToken:
          $ref: '#/definitions/KujiraBaseToken'
      quoteToken:
          $ref: '#/definitions/KujiraQuoteToken'
      precision:
        type: integer
        example: 3
      minimumOrderSize:
        type: string
        example: "0.001"
      minimumPriceIncrement:
        type: string
        example: "0.001"
      minimumBaseAmountIncrement:
        type: string
        example: "0.001"
      minimumQuoteAmountIncrement:
        type: string
        example: "0.001"
      fees:
        $ref: './definitions.yml#/definitions/KujiraFees'
  #  MarketsResponse:
#    type: "object"
#    properties:
#      // Define properties for MarketsResponse
#  AllMarketsResponse:
#    type: "object"
#    properties:
#      // Define properties for AllMarketsResponse
#  OrderBookResponse:
#    type: object
#    properties:
#      // Define properties for OrderBookResponse
#  OrderBooksResponse:
#    type: object
#    properties:
#      // Define properties for OrderBooksResponse
#  AllOrderBooksResponse:
#    type: object
#    properties:
#      // Define properties for AllOrderBooksResponse
#  TickerResponse:
#    type: object
#    properties:
#      // Define properties for TickerResponse
#  TickersResponse:
#    type: object
#    properties:
#      // Define properties for TickersResponse
#  AllTickersResponse:
#    type: object
#    properties:
#      // Define properties for AllTickersResponse
#  BalanceResponse:
#    type: object
#    properties:
#      // Define properties for BalanceResponse
#  BalancesResponse:
#    type: object
#    properties:
#      // Define properties for BalancesResponse
#  AllBalancesResponse:
#    type: object
#    properties:
#      // Define properties for AllBalancesResponse
#  OrderResponse:
#    type: object
#    properties:
#      // Define properties for OrderResponse
#  OrdersResponse:
#    type: object
#    properties:
#      // Define properties for OrdersResponse
#  PlaceOrderRequest:
#    type: object
#    properties:
#      // Define properties for PlaceOrderRequest
#  PlaceOrderResponse:
#    type: object
#    properties:
#      // Define properties for PlaceOrderResponse
#  PlaceOrdersRequest:
#    type: object
#    properties:
#      // Define properties for PlaceOrdersRequest
#  PlaceOrdersResponse:
#    type: object
#    properties:
#      // Define properties for PlaceOrdersResponse
#  CancelOrderRequest:
#    type: object
#    properties:
#      // Define properties for CancelOrderRequest
#  CancelOrderResponse:
#    type: object
#    properties:
#      // Define properties for CancelOrderResponse
#  CancelOrdersRequest:
#    type: object
#    properties:
#      // Define properties for CancelOrdersRequest
#  CancelOrdersResponse:
#    type: object
#    properties:
#      // Define properties for CancelOrdersResponse
#  CancelAllOrdersResponse:
#    type: object
#    properties:
#      // Define properties for CancelAllOrdersResponse
#  MarketWithdrawRequest:
#    type: object
#    properties:
#      // Define properties for MarketWithdrawRequest
#  MarketWithdrawResponse:
#    type: object
#    properties:
#      // Define properties for MarketWithdrawResponse
#  MarketsWithdrawsRequest:
#    type: object
#    properties:
#      // Define properties for MarketsWithdrawsRequest
#  MarketsWithdrawsFundsResponse:
#    type: object
#    properties:
#      // Define properties for MarketsWithdrawsFundsResponse
#  AllMarketsWithdrawsResponse:
#    type: object
#    properties:
#      // Define properties for AllMarketsWithdrawsResponse
#  TransactionResponse:
#    type: object
#    properties:
#      // Define properties for TransactionResponse
#  TransactionsResponse:
#    type: object
#    properties:
#      // Define properties for TransactionsResponse
#  WalletPublicKeyResponse:
#    type: object
#    properties:
#      // Define properties for WalletPublicKeyResponse
#  WalletsPublicKeysResponse:
#    type: object
#    properties:
#      // Define properties for WalletsPublicKeysResponse
#  CurrentBlockResponse:
#    type: object
#    properties:
#      // Define properties for CurrentBlockResponse
#  EstimatedFeesResponse:
#    type: object
#    properties:
#      // Define properties for EstimatedFeesResponse

  KujiraBaseToken:
    type: "object"
    $ref: './definitions.yml#/definitions/KujiraTokenResponse_1'

  KujiraQuoteToken:
    type: "object"
    $ref: './definitions.yml#/definitions/KujiraTokenResponse_2'